//! Reproducible operation catalogue generation; no runtime toolchain invocation.
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    fs,
    path::Path,
};

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Manifest {
    format: String,
    contract: String,
    revision: u64,
    schema_hash: String,
    families: Vec<Family>,
    operations: Vec<Operation>,
}
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Family {
    id: String,
    request_id_path: Option<Vec<String>>,
}
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Operation {
    name: String,
    domain: String,
    family: Option<String>,
    method: String,
    api_path: String,
    aliases: Vec<String>,
    kind: String,
    sse: bool,
    query: Vec<String>,
    request: Option<String>,
    response: Option<String>,
    etag_path: Option<Vec<String>>,
    expected_revision: Option<ExpectedRevision>,
}
#[derive(Deserialize)]
struct ExpectedRevision {
    path: Vec<String>,
    kind: String,
}

fn optional(value: Option<&str>) -> String {
    value.map_or_else(|| "None".into(), |value| format!("Some({value:?})"))
}
fn list(values: &[String]) -> String {
    format!(
        "&[{}]",
        values
            .iter()
            .map(|value| format!("{value:?}"))
            .collect::<Vec<_>>()
            .join(", ")
    )
}
fn params(path: &str) -> Vec<&str> {
    path.split('/')
        .filter_map(|segment| segment.strip_prefix(':'))
        .collect()
}
fn valid_key_path(path: &Option<Vec<String>>) -> bool {
    path.as_ref().is_none_or(|path| {
        !path.is_empty()
            && path.len() <= 8
            && path.iter().all(|key| {
                !key.is_empty()
                    && key.len() <= 64
                    && key
                        .bytes()
                        .next()
                        .is_some_and(|byte| byte.is_ascii_alphabetic())
                    && key.bytes().all(|byte| byte.is_ascii_alphanumeric())
            })
    })
}

pub fn render(raw: &[u8]) -> Result<String, String> {
    let manifest: Manifest = serde_json::from_slice(raw).map_err(|error| error.to_string())?;
    if manifest.format != "tansr-api-manifest-v1" || manifest.contract != "unified-v1" {
        return Err("unsupported manifest identity".into());
    }
    let mut names = BTreeSet::new();
    let mut families = BTreeMap::new();
    for family in &manifest.families {
        if families.insert(family.id.as_str(), family).is_some()
            || !valid_key_path(&family.request_id_path)
        {
            return Err(format!("invalid or duplicate family {}", family.id));
        }
    }
    for operation in &manifest.operations {
        if !names.insert(&operation.name)
            || !operation.api_path.starts_with("/api/")
            || operation.sse != (operation.kind == "stream")
            || !["GET", "POST", "DELETE"].contains(&operation.method.as_str())
            || !["read", "write", "stream"].contains(&operation.kind.as_str())
        {
            return Err(format!("invalid operation {}", operation.name));
        }
        if operation.aliases.iter().any(|alias| {
            !alias.starts_with("/api/") || params(alias) != params(&operation.api_path)
        }) {
            return Err(format!("invalid aliases for {}", operation.name));
        }
        if operation
            .family
            .as_ref()
            .is_some_and(|family| !families.contains_key(family.as_str()))
            || !valid_key_path(&operation.etag_path)
        {
            return Err(format!(
                "invalid family or ETag mapping for {}",
                operation.name
            ));
        }
        if operation
            .expected_revision
            .as_ref()
            .is_some_and(|revision| {
                operation.kind != "write"
                    || !["integer", "sequence"].contains(&revision.kind.as_str())
                    || !valid_key_path(&Some(revision.path.clone()))
            })
        {
            return Err(format!("invalid revision mapping for {}", operation.name));
        }
    }
    let mut out = String::new();
    writeln!(
        out,
        "// Generated by `cargo run -p xtask -- generate`; DO NOT EDIT."
    )
    .unwrap();
    writeln!(
        out,
        "// Source: contract/api-manifest.json, SHA256 {:x}\n",
        Sha256::digest(raw)
    )
    .unwrap();
    // rustfmt skip makes the generated bytes independent of the installed formatter release.

    writeln!(
        out,
        "#[rustfmt::skip]\npub const MANIFEST_REVISION: u64 = {};",
        manifest.revision
    )
    .unwrap();
    writeln!(
        out,
        "#[rustfmt::skip]\npub const SCHEMA_HASH: &str = {:?};",
        manifest.schema_hash
    )
    .unwrap();
    writeln!(
        out,
        "#[rustfmt::skip]\npub const MANIFEST_SHA256: &str = \"{:x}\";\n",
        Sha256::digest(raw)
    )
    .unwrap();
    out.push_str("#[rustfmt::skip]\n#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub struct ExpectedRevision { pub path: &'static [&'static str], pub kind: &'static str }\n\n");
    out.push_str("#[rustfmt::skip]\n#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub struct Operation {\n    pub name: &'static str,\n    pub domain: &'static str,\n    pub family: Option<&'static str>,\n    pub method: &'static str,\n    pub path: &'static str,\n    pub kind: &'static str,\n    pub sse: bool,\n    pub query: &'static [&'static str],\n    pub fenced: bool,\n    pub request_schema: Option<&'static str>,\n    pub response_schema: Option<&'static str>,\n    pub request_id_path: &'static [&'static str],\n    pub etag_path: &'static [&'static str],\n    pub expected_revision: Option<ExpectedRevision>,\n}\n\n");
    out.push_str("/// Find a manifest operation by its stable name.\n#[rustfmt::skip]\npub fn get(name: &str) -> Option<&'static Operation> { OPERATIONS.iter().find(|operation| operation.name == name) }\n\n/// The immutable manifest-order catalogue.\n#[rustfmt::skip]\npub fn operations() -> &'static [Operation] { OPERATIONS }\n\n");
    out.push_str("#[rustfmt::skip]\nconst OPERATIONS: &[Operation] = &[\n");
    for operation in manifest.operations {
        let family = operation
            .family
            .as_ref()
            .and_then(|family| families.get(family.as_str()));
        let request_id = family
            .and_then(|family| family.request_id_path.as_deref())
            .unwrap_or_default();
        let revision = operation.expected_revision.as_ref().map_or_else(
            || "None".into(),
            |revision| {
                format!(
                    "Some(ExpectedRevision {{ path: {}, kind: {:?} }})",
                    list(&revision.path),
                    revision.kind
                )
            },
        );
        let fenced = operation.domain != "discovery" && operation.name != "session.capabilities";
        writeln!(out, "    Operation {{ name: {:?}, domain: {:?}, family: {}, method: {:?}, path: {:?}, kind: {:?}, sse: {}, query: {}, fenced: {}, request_schema: {}, response_schema: {}, request_id_path: {}, etag_path: {}, expected_revision: {} }},", operation.name, operation.domain, optional(operation.family.as_deref()), operation.method, operation.api_path, operation.kind, operation.sse, list(&operation.query), fenced, optional(operation.request.as_deref()), optional(operation.response.as_deref()), list(request_id), list(operation.etag_path.as_deref().unwrap_or_default()), revision).unwrap();
    }
    out.push_str("];\n");
    Ok(out)
}

pub fn generate(root: &Path, check: bool) -> Result<(), String> {
    let source =
        fs::read(root.join("contract/api-manifest.json")).map_err(|error| error.to_string())?;
    let generated = render(&source)?;
    let target = root.join("src/api/operations.rs");
    if check {
        let actual = fs::read(&target).map_err(|error| error.to_string())?;
        if actual != generated.as_bytes() {
            return Err("operation catalogue drift; run cargo run -p xtask -- generate".into());
        }
    } else {
        fs::write(&target, generated).map_err(|error| error.to_string())?;
    }
    println!(
        "operation catalogue {}",
        if check { "verified" } else { "generated" }
    );
    Ok(())
}
